# Reboot Debian Flavored Linux Systems using the WHEN operator 
---
- hosts: all
  vars:
    is_enabled: true
  tasks:
    - name: "Tell only DevOps People Hello"
      shell: echo "Hello DevOps Readers"
      when: is_enabled is undefined
    - name: "This is Positive condition"
      shell: echo "is_enabled is defined"
      when: is_enabled
    - name: "Condition으로 반복"
      command: echo {{item}}
      with_items: [1,2,3,4,5,6,7,8,9,10]
      when: item >7
