- hosts: ip0* 
  tasks: 
  - name: 파일 리스트 저장
    command: ls /tmp/backup
    register: list_files 
  - debug: msg='{{ list_files.stdout_lines }}'
  - name: 파일이 있을까..
    assert:
      that:
      - "'no_crontab' in list_files.stdout_lines"