---
- hosts: ip0*
  tasks:
    - name: "/tmp/ok파일 존재"
      file:
        name: /tmp/ok
        state: touch
      tags:
        - file_exists
    - name: "/tmp/ok파일 없음"
      file:
        name: /tmp/ok
        state: absent
      tags:
        - file_absent