---
- hosts: ip0*
  tasks: 
    # 이 샘플은 exception 처리를 위한 예제이다. package check는 yum module로 합시다. command로 하는 것은 권장안함
    - name: 'jdk 체크'
      command: rpm -q java-1.8.0-openjdk-devel-1.8.0.151-1.b12.el7_4.x86_64
      register: "checkJDK_result"
      ignore_errors: true
      changed_when: checkJDK_result|failed
      tags :
        - check_jdk
    - name: "jdk 설치확인"
      block:
        - uri:
            url: http://mirror.centos.org/centos/7/updates/x86_64/Packages/java-1.8.0-openjdk-devel-1.8.0.151-1.b12.el7_4.x86_64.rpm
            method: GET
            dest: /tmp
            creates: /tmp/java-1.8.0-openjdk-devel-1.8.0.151-1.b12.el7_4.x86_64.rpm
        - yum:
            name: /tmp/java-1.8.0-openjdk-devel-1.8.0.151-1.b12.el7_4.x86_64.rpm
            state: present
        - alternatives:
            path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.x86_64/jre/bin/java
            name: java
            link: /usr/bin/java
        - alternatives:
            path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.x86_64/bin/javac
            name: javac
            link: /usr/bin/javac
        - file:
            name: /tmp/java-1.8.0-openjdk-devel-1.8.0.151-1.b12.el7_4.x86_64.rpm
            state: absent
      become: true
      when: checkJDK_result|failed