---
- hosts: webserver
  tasks:
    - name: "Apache 설치"
      yum:
        name: httpd
        state: present
      become: true
    - name: "Apache 시작"
      service:
        name: httpd
        state: started
        enabled: true
      become: true
    - name: "http firewall해제"
      firewalld:
        service: '{{ item }}'
        state: enabled
        permanent: true
        immediate: true
      become: true
      with_items:
      - http
      - https
#    - name: "https firewall해제"
#      firewalld:
#        service: https
#        state: enabled
#        permanent: true
#        immediate: true
#      become: true