---
- hosts: ip0*
  vars:
    users:
    - alice
    - bob
    folders:
    - mail
    - public_html
  tasks:
    - name: "user 있어야함."
      user:
        name: '{{ item }}'
      become: true
      with_items:
      - '{{ users }}'
    - name: "폴더 존재."
      file:
        path: '/home/{{ item.0 }}/{{ item.1}}'
        state: directory
        owner: '{{ item.0 }}'
        group: '{{ item.0 }}'
      become: true
      with_nested:
      - '{{ users }}'
      - '{{ folders }}'