---
- hosts: ip0*
  tasks:
    - name: "/tmp/ymls 폴더 준비"
      file:
        name: /tmp/ymls
        state: directory
      become: true
    - name: "local의 yml파일들을 모두 복사"
      copy: 
        src: '{{ item }}' 
        dest: '/tmp/ymls'  
      become: true 
      with_fileglob: 
      - '*.yml'