---
- hosts: ip0*
  tasks:
    - name: "/tmp밑에 폴더 10개 존재"
      file:
        name: '/tmp/folder{{ item }}'
        state: directory
        owner: 'alice'
        group: 'bob'
      with_sequence: start=1 end=10
      become: true
