---
- hosts: ip0*
  tasks:
    - name: "ip0에서 실행되는 process 개수"
      shell: ps -e|wc -l
      register: remote_processes_number
    - name: "ip0 process 개수 출력"
      debug:
        msg: '{{ remote_processes_number.stdout }}'
    - name: "vm1의 process 개수를 delegate해서.."
      shell: ps -e|wc -l
      # ip0의 입장에서 어디로 접속하느냐? 이기 때문에..
      # 지금은 이 예제는 실행 오류 발생함. 왜?
      delegate_to: 192.168.0.6
      register: vm1_processes_number
    - name: "vm1 process 개수 출력"
      debug:
        msg: '{{ vm1_processes_number }}'