---
- hosts: ip0*
  tasks:
    - name: "OS 종류 확인"
      debug:
        msg: 'OS는 {{ ansible_os_family }} 입니다'
    - name: "RedHat httpd 설치확인"
      yum:
        name: httpd
        state: latest
      become: true
      when: ansible_os_family == 'RedHat'
    - name: "Debian apache 설치확인"
      apt:
        name: apache2
        state: latest
      become: true
      when: ansible_os_family == 'Debian'