---
- hosts: ip0*
  tasks:
    - name : "샘플 index.html 배포"
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      become: true
