---
- hosts: all
  tasks:
    - name: "NTP 설정"
      yum:
        name: ntp
        state: present
      become: true
    - name: "NTP 띄우기"
      service:
        name: ntpd
        state: started
        enabled: true
      become: true
