---
- hosts: all
  tasks:
    - name: "timezone 설정"
      file:
        src: /usr/share/zoneinfo/Asia/Seoul
        dest: /etc/localtime
        # symbolic link로 만듬
        state: link
      become: true
