---
- hosts: all
  tasks:
    - name: "firewalld 설치"
      yum:
        name: firewalld
        state: present
      become: true
    - name: "Locale관련 오류 수정. 이 부분이 수정안되면 마지막 firewalld에서 ssh enable에서 오류발생함. 아마도 exit code를 보는 듯."
      lineinfile: 
        dest: /etc/environment 
        state: present 
        #아래와 같은 조건을 찾아서..
        regexp: '^LANG\=' 
        #없으면 아래 라인을 추가한다. 있으면 대치한다. 
        line: 'LANG=en_US.utf-8'
      become: true
    - name: "firewalld 띄우기"
      service:
        name: firewalld
        state: started
        enabled: true
      become: true
    - name: "그래도 ssh는 되어야함"
      firewalld:
        service: ssh
        state: enabled
        permanent: true
        immediate: true
      become: true
