---
- hosts: ip0*
  tasks:
    - name: "EPEL 설치"
      yum:
        name: epel-release
        state: present
      become: true
    - name: "libselinux-python 설치"
    # for ansible
      yum:
        name: libselinux-python
        state: present
      become: true
    - name: "libsemanage-python 설치"
    # for ansible
      yum:
        name: libsemanage-python
        state: present
      become: true
    - name: "Package 모두 update"
      yum:
        name: "*"
        state: latest
      become: true
    - name: "NTP 설정"
      yum:
        name: ntp
        state: present
      become: true
    - name: "NTP 띄우기"
      service:
        name: ntpd
        state: started
        enabled: true
      become: true
    - name: "timezone 설정"
      file:
        src: /usr/share/zoneinfo/Asia/Seoul
        dest: /etc/localtime
        # symbolic link로 만듬
        state: link
      become: true
    - name: "firewalld 설치"
      yum:
        name: firewalld
        state: present
      become: true
    - name: "Locale관련 오류 수정."
      #이 부분이 수정안되면 마지막 firewalld에서 ssh enable에서 오류발생함. 아마도 exit code를 보는 듯.
      lineinfile: 
        dest: /etc/environment 
        state: present 
        #아래와 같은 조건을 찾아서..
        regexp: '^LANG\=' 
        #없으면 아래 라인을 추가한다. 있으면 대치한다. 
        line: 'LANG=en_US.utf-8'
      become: true
    - name: "firewalld 띄우기"
      service:
        name: firewalld
        state: started
        enabled: true
      become: true
    - name: "그래도 ssh는 되어야함"
      firewalld:
        service: ssh
        state: enabled
        permanent: true
        immediate: true
      become: true
    - name: "MOTD 바꾸기"
      template:
        src: 07motd
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
      become: true
    - name : "hostname을 dns host명과 일치시킴"
      hostname:
        name: "{{ inventory_hostname }}"
      become: true
